version: '3'
services:
  postgres-db:
    image: 'postgres:14-alpine'
    container_name: "book-db"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stork
    ports:
      - 5432:5432
  app:
    image: your-books:latest
    container_name: your-books-server
    ports:
      - 8080:8080
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db:5432/postgres
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=postgres
        - SPRING_JPA_HIBERNATE_DDL_AUTO=create
    depends_on:
      - postgres-db

